# Generated by Django 3.1.4 on 2021-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViloSkyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RadioButtonsAdminInput',
            new_name='MultiselectAdminInput',
        ),
        migrations.AlterField(
            model_name='admininput',
            name='input_type',
            field=models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('CHECKBOX', 'Checkbox'), ('MULTISELECT', 'Multiselect')], max_length=255),
        ),
    ]
