# Generated by Django 3.1.4 on 2021-01-18 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViloSkyApp', '0002_auto_20210106_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('CHECKBOX', 'Checkbox')], max_length=255)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='middleNames',
            new_name='middle_names',
        ),
        migrations.AddField(
            model_name='report',
            name='datetime_created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_made', to='ViloSkyApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckboxAdminInput',
            fields=[
                ('admin_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViloSkyApp.admininput')),
                ('default_value', models.BooleanField(default=False)),
            ],
            bases=('ViloSkyApp.admininput',),
        ),
        migrations.CreateModel(
            name='DropdownAdminInput',
            fields=[
                ('admin_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViloSkyApp.admininput')),
                ('choices', models.JSONField()),
            ],
            bases=('ViloSkyApp.admininput',),
        ),
        migrations.CreateModel(
            name='TextAdminInput',
            fields=[
                ('admin_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViloSkyApp.admininput')),
                ('max_length', models.PositiveIntegerField(null=True)),
            ],
            bases=('ViloSkyApp.admininput',),
        ),
        migrations.CreateModel(
            name='TextareaAdminInput',
            fields=[
                ('admin_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViloSkyApp.admininput')),
                ('max_length', models.PositiveIntegerField(null=True)),
            ],
            bases=('ViloSkyApp.admininput',),
        ),
        migrations.CreateModel(
            name='PartialInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('admin_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_inputs', to='ViloSkyApp.admininput')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_input_created', to='ViloSkyApp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='admininput',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_inputs_created', to='ViloSkyApp.userprofile'),
        ),
    ]
