# Generated by Django 3.1.4 on 2021-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViloSkyApp', '0005_auto_20210122_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_worked_in_industry',
            field=models.CharField(blank=True, choices=[('No experience', 'No Experience'), ('1-6 Months', 'One To Six Months'), ('7-12 Months', 'Seven To Twelve Months'), ('1-2 Years', 'One To Two Years'), ('3-5 Years', 'Three To Five Years'), ('5-10 Years', 'Five To Ten Years'), ('10+ Years', 'Ten Plus Years')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
