# Generated by Django 3.1.4 on 2021-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViloSkyApp', '0006_auto_20210127_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Unemployed/Volunteer', 'Unemployed Or Volunteer'), ('Employed', 'Employed'), ('Self-Employed', 'Selfemployed'), ('Career Break', 'Career Break'), ('Retired', 'Retired')], max_length=255),
        ),
    ]
