# Generated by Django 3.1.4 on 2021-03-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViloSkyApp', '0007_auto_20210304_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioButtonsAdminInput',
            fields=[
                ('admin_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ViloSkyApp.admininput')),
                ('choices', models.JSONField()),
            ],
            bases=('ViloSkyApp.admininput',),
        ),
        migrations.AlterField(
            model_name='admininput',
            name='input_type',
            field=models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('CHECKBOX', 'Checkbox'), ('RADIOBUTTONS', 'Radiobuttons')], max_length=255),
        ),
    ]
